name: Compilation & tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build_application:
    name: Build application using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
    with:
      upload_app_binaries_artifact: "compiled_app_binaries"

  build_debug_application:
    name: Build debug application using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
    with:
      upload_app_binaries_artifact: "compiled_dbg_app_binaries"
      flags: "DEVEL=1"

  job_speculos_unit_tests_5001:
    name: ${{ matrix.target_device }} Speculos 5001 unit tests
    needs: build_debug_application
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target_device: ["NANO_X", "NANO_SP"]
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.10.0
      - name: Download app binary
        uses: actions/download-artifact@v4
        with:
          name: compiled_dbg_app_binaries
          path: build

      - name: install speculos
        run: |
          export BOLOS_SDK=
          make js-yarn
          make test-yarn
      - name: Run tests
        run: |
          TARGET_DEVICE=${{ matrix.target_device }} make speculos_port_5001_unit_test
      - name: Upload Speculos 5001 log
        uses: actions/upload-artifact@v4
        with:
          name: speculos-ut-5001-${{ matrix.target_device }}-log
          path: tests_speculos/speculos-port-5001.log

  job_speculos_tests_5001:
    name: ${{ matrix.target_device }} Speculos 5001 tests
    needs: build_debug_application
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target_device: ["NANO_X", "NANO_SP"]
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.10.0
      - name: Download app binary
        uses: actions/download-artifact@v4
        with:
          name: compiled_dbg_app_binaries
          path: build

      - name: install speculos
        run: |
          export BOLOS_SDK=
          make js-yarn
          make test-yarn
      - name: Run tests
        run: |
          TARGET_DEVICE=${{ matrix.target_device }} make speculos_port_5001_test
      - name: Upload Speculos 5001 log
        uses: actions/upload-artifact@v4
        with:
          name: speculos-5001-${{ matrix.target_device }}-log
          path: tests_speculos/speculos-port-5001.log

